### ISSUE TITLE
Question/request: publish npm pkg

### ISSUE THREAD

**Issue by danwild** [Asymmetrik/leaflet-d3#15]
Hey, this looks great - thanks!

I see this project has a package.json file; however I [can't see it in npm registry](https://www.npmjs.com/search?q=leaflet-d3).
Has this been published to npm?

Cheers,
Dan

**Comment by reblace** [comment]
I'm currently refactoring another project to support npm/jspm repositories, so this one should get that treatment soonish. Thanks for the feedback!

**Comment by danwild** [comment]
Great, thanks for the heads up 👍

**Comment by reblace** [comment]
I just tagged a 1.0.0 release that supports d3 v4 and leaflet 1.0. I also switched to npm deployments and the whole thing bundles to umd now, so it should work both as a global import as well as with module loaders. A typings file should be coming relatively soon.
