### ISSUE TITLE
Request: update to d3 v4

### ISSUE THREAD

**Issue by warrenronsiek** [Asymmetrik/leaflet-d3#18]
Hi, compatibility with D3 version 4 would be awesome when you get around to it. Thank you!

**Comment by reblace** [comment]
I just tagged a 1.0.0 release that supports d3 v4 and leaflet 1.0. I also switched to npm deployments and the whole thing bundles to umd now, so it should work both as a global import as well as with module loaders. A typings file should be coming relatively soon.
