### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by sumrakx** [Asymmetrik/leaflet-d3#23]
Your code on demonstration variant work incorrect...

**Comment by reblace** [comment]
Can you provide more information? I can't tell what the specific issue you are reporting is.

**Comment by reblace** [comment]
I actually see that there's an issue with the hexbins. D3 Hexbin changed the exported global namespace of the module. I've fixed it and will have a new patch release out shortly. Thanks for the issue report. If this is not the issue you were reporting, please provide more info.

**Comment by reblace** [comment]
New version (1.2.1) is published to NPM, should fix the broken hexbin layer with the latest d3 hexbin plugin.
