### ISSUE TITLE
JSFiddle for hexbin is misleading

### ISSUE THREAD

**Issue by vgrichina** [Asymmetrik/leaflet-d3#35]
This JSFiddle http://jsfiddle.net/reblace/acjnbu8t/ provides example which gives misleading (likely just outdated, as it used to work before) info on how to initialize `lat`/`lng`/`value` functions.

```js
var options = {
    radius : 12,
    opacity: 0.5,
    duration: 500,
    lng: function(d){
        return d[0];
    },
    lat: function(d){
        return d[1];
    },
    value: function(d){
        return d.length;
    },
    valueFloor: 0,
    valueCeil: undefined
};

var hexLayer = L.hexbinLayer(options).addTo(map)
```

Functions `lat`, `lng`, `value` are just ignored when given in initial options. To make them used one has to call setters.

**Comment by reblace** [comment]
You are 100% correct, I totally forgot to update the fiddle when I updated the API. I think it's correct now. I've added stuff that shows how to size the hexbins as well as coloring them. Thanks for the catch!
