### ISSUE TITLE
Provide explicitly the domain of the color scale for Hexbin Layer

### ISSUE THREAD

**Issue by ninio** [Asymmetrik/leaflet-d3#47]
I am trying to use the Hexbin layer with a number of colors that are not evenly distributed over the values domain. 
Due to this I'd be happy to be able to set the colors scale domain manually.

Do you think adding an option `manualColorScaleDomain` that is checked before setting the domain in [HexbinLayer.js:208](https://github.com/Asymmetrik/leaflet-d3/blob/609edd0b9020ef0c26970613d9f654a2a2789694/src/js/hexbin/HexbinLayer.js#L208) is good enough?

Nice library, btw : )

**Comment by reblace** [comment]
Let me know if 4.1.0 gives you what you need. If not, I'll have to think about it a bit to see if there's a cleaner way to allow full manual config of the scales.

**Comment by reblace** [comment]
Haven't heard anything more. Open a new issue if you have any other requests/issues. Thanks!
