### ISSUE TITLE
Proposal new methods .hide(), .show()

### ISSUE THREAD

**Issue by stefanocudini** [Asymmetrik/leaflet-d3#54]
I need of show and hide the d3 hexagon at runtime.. here in my new project: [keplerjs.io](http://keplerjs.io/)

```javascript
L.HexbinLayer = L.HexbinLayer.extend({
	show: function(map) {
		if(this._dataOld) {
			this._data = this._dataOld;
			delete this._dataOld;
		}
		this.redraw();
	},
	hide: function(map) {
		if(!this._dataOld) {
			this._dataOld = this._data;
			this._data = [];
		}
		this.redraw();
	}	
});
```

**Comment by reblace** [comment]
The goal of the d3 layer is to keep the API simple and limit the number of ways you do common things. In this case, if your goal is to show/hide the hexbins, the two recommended ways to do are:

1. Keep a copy of the data outside the layer and then pass in either the data or an empty array to "show/hide" the hexbins
2. Remove the layer from the map to "show/hide" the hexbins

**Comment by stefanocudini** [comment]
map.addLayer(hexbin) and map.removeLayer(hexbin) not work... :( 

look at here:
https://github.com/Asymmetrik/leaflet-d3/blob/master/src/js/hexbin/HexbinLayer.js#L130

**Comment by reblace** [comment]
If your desire is to keep the layer on the map, but change the data, call `layer.data(newData);` to cause the hexbins to update. In this case, the internal data array is updated. You could pass in an empty array to effectively "clear" the map this way.

If all you want to do is toggle the visibility of the layer, you should use `map.removeLayer(layer)` and `map.addLayer(layer)`. That is exactly what happens if you add this layer as an overlay using the Layers Control (Control.Layers) and then turn it on and off. In this case, the state of the layer isn't changed at all. Rather, it's just added or removed from the map.

This is the desired behavior and standard behavior among similar things like Marker Cluster layers and LayerGroups.

**Comment by reblace** [comment]
The reason this `//this._data = [];` line is commented out is because it was commented out to fix a bug where using a layers control to toggle the visibility of the layer would clear the data (which was not the intended behavior). Those lines should be removed from the code at this point.

**Comment by statzg** [comment]
The current function for removing the hexbin doesn't work with Layers Control, at least not in ff. The layer is still visible and still reacts to zoom. 
Adding `d3.select(this._container).remove();` after `this._map = null;` fixes the problem for me. Now controls work as expected.

**Comment by reblace** [comment]
@statzg Can you provide some code to illustrate what you're talking about?

**Comment by statzg** [comment]
Here is the entire onRemove:

`		onRemove : function(map) {

			L.SVG.prototype.onRemove.call(this);

			// Destroy the svg container
			this._destroyContainer();

			// Remove events
			map.off({ 'moveend': this.redraw }, this);
			
			this._map = null;
			
			d3.select(this._container).remove();

			// Explicitly will leave the data array alone in case the layer will be shown again
			//this._data = [];

		}`

**Comment by whittaker007** [comment]
I am trying to turn the Hexbin layer on and off depending on the zoom level of the map. Adding the hexbin layer with map.addLayer(hexLayer) does indeed show the hexes, but removing it again with map.removeLayer(hexLayer) leaves the last rendered hexes on the map, though they no longer update with the new zoom level. 

Removing the layer should also remove the hexes from the screen.

**Comment by whittaker007** [comment]
In case anyone else has this issue I used the above code to modify the class prototype on the fly:

L.HexbinLayer.prototype.onRemove = function(map) {
  L.SVG.prototype.onRemove.call(this);
  // Destroy the svg container
  this._destroyContainer();
  // Remove events
  map.off({ 'moveend': this.redraw }, this);
  this._map = null;
  // Explicitly will leave the data array alone in case the layer will be shown again
  //this._data = [];
  d3.select(this._container).remove();
};
