### ISSUE TITLE
Hexagons vanish if they are half outside the visible map extents

### ISSUE THREAD

**Issue by kannes** [Asymmetrik/leaflet-d3#55]
I made a map with hexagons on it.
The user can move the map so that hexagons intersect the borders of the map.
Hexagons are shown if they are partially outside the map, so they are partially cut off.
Once more than half of their symbol is outside the map, the whole hexagon will vanish.

The hexagons should only vanish if fully outside the map.

I guess this is a check using the centroids of the hexagons instead of their min/max coordinates?

Before panning:
![before move](https://user-images.githubusercontent.com/7661092/43961122-63f75500-9cb4-11e8-92fb-56d5e0e89edd.png)

After panning (the bottom row of hexagons is gone, letting the white map background through):
![after move](https://user-images.githubusercontent.com/7661092/43961127-66f24580-9cb4-11e8-9c1d-a23e88173831.png)

**Comment by reblace** [comment]
Hmm.... ok. It's supposed to only hide them if they are outside of the external boundaries. I'll take a look.

**Comment by kannes** [comment]
Works like a charm, thank you for this quick fix!
