### ISSUE TITLE
Readme instructions should be updated to include build line

### ISSUE THREAD

**Issue by whittaker007** [Asymmetrik/leaflet-d3#59]
I see the dist folder was removed a few days ago, now none of the examples work. 

The readme instructions say to install d3, d3-hexbin and leaflet. However this is insufficient and you need to build the dist folder with:

npm run build

This may be obvious to regular npm users, but for noobs like me it's not obvious and took a few minutes of googling to figure out, and I'm a longtime web dev, I just don't use npm that much yet.

**Comment by reblace** [comment]
Good catch, thanks I'll update the docs.
