### ISSUE TITLE
Hexbin demo link on JSFiddle no longer works

### ISSUE THREAD

**Issue by jay-jlm** [Asymmetrik/leaflet-d3#62]
No overlay is displayed even after I click the generated data button.

Got the following errors on the JS console:
```
Failed to load resource: the server responded with a status of 404 ()
(index):62 Uncaught TypeError: L.hexbinLayer is not a function
    at (index):62
2(index):39 Uncaught TypeError: generateData is not a function
    at HTMLButtonElement.onclick ((index):39)
```

Link: http://jsfiddle.net/acjnbu8t/embedded/result/

**Comment by reblace** [comment]
Thanks for the heads up. I fixed both of the fiddle examples to work with the most recent versions.
