### ISSUE TITLE
Properly removing layer from map 

### ISSUE THREAD

**Issue by do-me** [Asymmetrik/leaflet-d3#68]
Whats the preferred way to remove the hexbinlayer from the map? 
When I call 
```
map.removeLayer(hexLayer);
``` 
or 

```
hexLayer.remove()
```
the hexbins of the current zoom level freeze and remain as an artifact on the map canvas. 

I can simply remove it on one zoom level only with `d3.selectAll("g").remove()` but is this really the 'proper' way?
I run into problems as I'm using geoman to draw polygons. It also uses `g` elements so everytime I call the above function I remove the polygon as well.
You can try with the standard hexbins [jsfiddle](http://jsfiddle.net/reblace/acjnbu8t/). 

I managed to access the parent element with `$( ".hexbin" ).parent( "g" ).remove()` so it behaves the way I want but still it doesn't seem elegant to me.

Additionally I noticed that after adding the layer to leaflet layer control the layer can't be turned off and behaves in the same way.

**Comment by reblace** [comment]
This is fixed now in v4.4.1. Sorry it took FOREVER to get around to fixing it.
