### ISSUE TITLE
pings don't move with map

### ISSUE THREAD

**Issue by wgmueller1** [Asymmetrik/leaflet-d3#8]
If you move the map the pings stay in place.

**Comment by reblace** [comment]
That was actually a design decision, so I'll leave it open and mark it as an enhancement.

**Comment by wgmueller1** [comment]
Thanks for the response.  It become noticable once you if you change the duration of the pings.  Was it just easier not to bind the pings to an overlay?

**Comment by reblace** [comment]
I didn't spend time investigating how to get it working as it wasn't a
priority for my use case. One potential issue is the efficiency of
recalculating the position of the circle on every tick. Though you would
only need to do that when the map is being moved. I may revisit it
eventually. If you find a solution feel free to submit a pull request.

Thanks for the response. It become noticable once you if you change the
duration of the pings. Was it just easier not to bind the pings to an
overlay?

—
Reply to this email directly or view it on GitHub
<https://github.com/Asymmetrik/leaflet-d3/issues/8#issuecomment-112071857>.

**Comment by reblace** [comment]
I updated the plugin to update the ping position when the map is moved. It does it immediately so the animation is smooth even when you're running at a reduced fps.
